find_path(WINPTY_INCLUDE_DIRS   winpty.h            ${WINPTY_CHECKOUT_PATH}/src/include)
find_file(WINPTY_DLL            winpty.dll          ${WINPTY_CHECKOUT_PATH}/build)
find_file(WINPTY_LIB            winpty.lib          ${WINPTY_CHECKOUT_PATH}/build)
find_file(WINPTY_AGENT_EXE      winpty-agent.exe    ${WINPTY_CHECKOUT_PATH}/build)
set(WINPTY_LIBRARIES            ${WINPTY_LIB})
set(WINPTY_BINARIES             ${WINPTY_DLL} ${WINPTY_AGENT_EXE})
